Link: https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

### Autograd

In [24]:
from __future__ import print_function
import torch
import numpy as np

In [2]:
torch.__version__

'1.3.0'

In [3]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.size())

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
torch.Size([2, 2])


In [4]:
y = x + 2
print(y)
print(y.size())

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
torch.Size([2, 2])


In [5]:
z = y*y*3
out = z.mean()

print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [6]:
# mutate in-place
a = torch.randn(2, 2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


### Backpropogation

In [7]:
out.backward()

In [8]:
# d(out)/dx
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [40]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([ 0.5489, -0.5355,  2.4153], requires_grad=True)


In [41]:
y = x * 2
print(y)

tensor([ 1.0978, -1.0710,  4.8306], grad_fn=<MulBackward0>)


In [42]:
y.data.norm()

tensor(5.0682)

In [43]:
np.sqrt((y**2).sum().item())

5.068166504940594

In [44]:
while y.data.norm() < 10:
    y = y * 2

In [45]:
print(y)

tensor([ 2.1955, -2.1419,  9.6611], grad_fn=<MulBackward0>)


In [49]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v, retain_graph=True)

print(x.grad)

tensor([1.6000e+00, 1.6000e+01, 1.6000e-03])


In [50]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


In [51]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
