Link: https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

### Target Audience
1. Replacement for numpy to run on GPU/TPU
2. Deep learning research platform with max flexiblity and speed

In [1]:
from __future__ import print_function
import torch

In [5]:
# Uninitialized matrix
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00, -1.6298e-21]])


In [8]:
# Randomly initialized matrix
x = torch.rand(5, 3)
print(x)

tensor([[0.2152, 0.4845, 0.4883],
        [0.0460, 0.7623, 0.0032],
        [0.5740, 0.3669, 0.0483],
        [0.8959, 0.4367, 0.1130],
        [0.1298, 0.1221, 0.5286]])


In [10]:
# Construct a matrix filled zeros and of dtype long
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [12]:
print(x.dtype)

torch.int64


In [14]:
# Construct a tensor directly from data
x = torch.tensor([10.0, 2])
print(x)

tensor([10.,  2.])


In [15]:
# create a tensor based on an existing tensor
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [16]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.2649,  0.0701,  1.5310],
        [ 1.0188,  1.4566, -1.2946],
        [ 0.4400,  1.1951,  0.2559],
        [ 1.9596,  1.1482, -0.2365],
        [ 1.5692, -0.7186, -1.0203]])


In [17]:
print(x.size())

torch.Size([5, 3])


### Addition Operation

In [21]:
y = torch.rand(5, 3)
print(x)
print(y)
print(x+y)
print(torch.add(x, y))

tensor([[ 0.2649,  0.0701,  1.5310],
        [ 1.0188,  1.4566, -1.2946],
        [ 0.4400,  1.1951,  0.2559],
        [ 1.9596,  1.1482, -0.2365],
        [ 1.5692, -0.7186, -1.0203]])
tensor([[0.7731, 0.3757, 0.4499],
        [0.5690, 0.6445, 0.5047],
        [0.2652, 0.5573, 0.7042],
        [0.4629, 0.1877, 0.5903],
        [0.1330, 0.6673, 0.4337]])
tensor([[ 1.0380,  0.4458,  1.9809],
        [ 1.5878,  2.1012, -0.7899],
        [ 0.7052,  1.7524,  0.9601],
        [ 2.4225,  1.3359,  0.3538],
        [ 1.7022, -0.0512, -0.5866]])
tensor([[ 1.0380,  0.4458,  1.9809],
        [ 1.5878,  2.1012, -0.7899],
        [ 0.7052,  1.7524,  0.9601],
        [ 2.4225,  1.3359,  0.3538],
        [ 1.7022, -0.0512, -0.5866]])


In [22]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.0380,  0.4458,  1.9809],
        [ 1.5878,  2.1012, -0.7899],
        [ 0.7052,  1.7524,  0.9601],
        [ 2.4225,  1.3359,  0.3538],
        [ 1.7022, -0.0512, -0.5866]])


In [23]:
# addition in place
y.add_(x)
print(y)

tensor([[ 1.0380,  0.4458,  1.9809],
        [ 1.5878,  2.1012, -0.7899],
        [ 0.7052,  1.7524,  0.9601],
        [ 2.4225,  1.3359,  0.3538],
        [ 1.7022, -0.0512, -0.5866]])


In [25]:
print(x)
print(x[:,1])
print(x[1, :])
print(x[1:3, :])

tensor([[ 0.2649,  0.0701,  1.5310],
        [ 1.0188,  1.4566, -1.2946],
        [ 0.4400,  1.1951,  0.2559],
        [ 1.9596,  1.1482, -0.2365],
        [ 1.5692, -0.7186, -1.0203]])
tensor([ 0.0701,  1.4566,  1.1951,  1.1482, -0.7186])
tensor([ 1.0188,  1.4566, -1.2946])
tensor([[ 1.0188,  1.4566, -1.2946],
        [ 0.4400,  1.1951,  0.2559]])


In [26]:
# Resizing
x = torch.randn(4, 4)
print(x)

tensor([[ 0.0323,  1.1845,  0.2345, -0.0448],
        [-1.4087,  0.8822,  0.8151,  0.8925],
        [ 0.0324, -0.0323,  1.1017,  1.4822],
        [-0.2746, -2.0895,  0.0588,  1.4040]])


In [27]:
y = x.view(16)
z = x.view(-1, 8)
print(y)
print(z)

tensor([ 0.0323,  1.1845,  0.2345, -0.0448, -1.4087,  0.8822,  0.8151,  0.8925,
         0.0324, -0.0323,  1.1017,  1.4822, -0.2746, -2.0895,  0.0588,  1.4040])
tensor([[ 0.0323,  1.1845,  0.2345, -0.0448, -1.4087,  0.8822,  0.8151,  0.8925],
        [ 0.0324, -0.0323,  1.1017,  1.4822, -0.2746, -2.0895,  0.0588,  1.4040]])


In [28]:
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [29]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.1368])
-1.1367782354354858


### Numpy Bridge

In [30]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [31]:
b = a.numpy()
print(a)

tensor([1., 1., 1., 1., 1.])


In [32]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [33]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [34]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to('cpu', dtype=torch.double))