In [1]:
sc = SparkContext.getOrCreate()

In [2]:
sc.applicationId

'local-1593008130934'

### Sparktorch
https://github.com/dmmiller612/sparktorch

In [4]:
import numpy as np

In [5]:
from torchvision import datasets, transforms

transform = transforms.Compose([transforms.ToTensor(),
                              transforms.Normalize((0.5,), (0.5,)),
                              ])

trainset = datasets.MNIST('./', download=True, train=True,
                          transform=transform)

In [6]:
n_samples, x, y = trainset.data.shape
x_train = trainset.data.reshape((n_samples, x*y))
x_train = x_train.numpy()
y_train = trainset.targets.numpy()

print(x_train, y_train)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] [5 0 4 ... 5 6 8]


In [7]:
# concatenate x_train and y_train
y_train = y_train.reshape((y_train.shape[0], 1))
print(y_train.shape)
train_data = np.concatenate((x_train, y_train), axis=1)
print(train_data.shape)
train_data

(60000, 1)
(60000, 785)


array([[0, 0, 0, ..., 0, 0, 5],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 4],
       ...,
       [0, 0, 0, ..., 0, 0, 5],
       [0, 0, 0, ..., 0, 0, 6],
       [0, 0, 0, ..., 0, 0, 8]])

In [8]:
num_cols = train_data.shape[1]
print(num_cols)

785


In [9]:
from sparktorch import serialize_torch_obj, SparkTorch
import torch
import torch.nn as nn
from pyspark.ml.feature import VectorAssembler
from pyspark.sql import SparkSession
from pyspark.ml.pipeline import Pipeline

spark = SparkSession.builder.appName("examples").getOrCreate()

In [10]:
train_data_sp = sc.parallelize(train_data)

In [11]:
train_data_sp.count()

KeyboardInterrupt: 